language: python
python:
- '2.7'
addons:
  postgresql: "9.3"
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- cd awesomemailer/
- python -m unittests
- python -m integrationtests
- python -m emailproviders.tests
- cd ../
deploy:
  provider: heroku
  api_key:
    secure: if/n5kZNprU5pePtxvQFRjWdNhO3hhY7I1HYB+9JkfQKKz5JWUebYz9WvuW45Kheq44y03wifgcjzRZuBf3chLz908z4HuujSQlZtQNu8NfDFfB3MhhpRvnZuyDsslwoj/ZuPp0CwympZ9OXUv86vsn2dKlebx5ZaX5OpTH+Fho=
  app: tranquil-lowlands-1979
